version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_user_service
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: user-service
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    container_name: adminer_user_service
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_user_data: